// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoAMGpIIFtMwn_pfTLXxp0SHO-2qEu8j4',
    appId: '1:499568652123:web:14910074aa6b2931c2347e',
    messagingSenderId: '499568652123',
    projectId: 'amanu-kpd',
    authDomain: 'amanu-kpd.firebaseapp.com',
    databaseURL: 'https://amanu-kpd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amanu-kpd.appspot.com',
    measurementId: 'G-E2XJCEXWYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJE_iDwHhgELmAVYlkDoGtiWmYK_UjV8g',
    appId: '1:499568652123:android:392fd7547bd1f64fc2347e',
    messagingSenderId: '499568652123',
    projectId: 'amanu-kpd',
    databaseURL: 'https://amanu-kpd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amanu-kpd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTinIRvlgn4f3fFYoaa7-Px4TQz6oIXUc',
    appId: '1:499568652123:ios:82b982a1cbd8438bc2347e',
    messagingSenderId: '499568652123',
    projectId: 'amanu-kpd',
    databaseURL: 'https://amanu-kpd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'amanu-kpd.appspot.com',
    iosClientId: '499568652123-7aht1987bmetgoagf2dbv82mcailhkvv.apps.googleusercontent.com',
    iosBundleId: 'com.hauckdogs.amanu',
  );
}
